on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: baguspramono
          password: dckr_pat_on_PdFpR-d1evE2jR9Ld4SvXtZQ

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: ./Dockerfile
          tags: baguspramono/ml-app:latest
          push: true  # This pushes the image to Docker Hub

      - name: Run Docker Container for Tests
        run: |
          docker run --rm user/ml-app:latest python -m unittest discover tests
